# Generated by Django 3.2.8 on 2021-11-09 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='content',
            new_name='comment',
        ),
    ]
