# Generated by Django 3.2.8 on 2021-11-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_content_blogcomment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
